import { Inter } from "next/font/google";
import "./globals.css";
import UserState from "@/context";
import CommonLayout from "@/components/common-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UserNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href="/favicon.png" />
      </head>
      <body className={inter.className}>
        <CommonLayout>
          {children}
        </CommonLayout>
      </body>
    </html>
  );
}
